export const commits = [
  {
    author: {
      name: 'Aleksey Gurianov',
      email: 'gurianov@gmail.com',
    },
    date: '2017-06-29T11:14:02.000Z',
    sha: 'c327edd6671b814b01f4d5c82a73cb4f8fb034b3',
    body: '',
    issues: [],
    breaks: [],
    type: 'chore',
    message: 'initial setup',
    files: [
      '.cz-config.js',
      '.eslintignore',
      '.eslintrc.json',
      '.gitattributes',
      '.gitignore',
      '.repo-cooker/link.js',
      '.repo-cooker/publish.js',
      'LICENSE',
      'README.md',
      'package.json',
      'packages/node_modules/@repo-cooker-test/commis/package.json',
      'packages/node_modules/@repo-cooker-test/entremetier/package.json',
      'packages/node_modules/@repo-cooker-test/executive-chef/package.json',
      'packages/node_modules/@repo-cooker-test/pastry-chef/package.json',
      'packages/node_modules/@repo-cooker-test/poissonier/package.json',
      'packages/node_modules/@repo-cooker-test/sous-chef/package.json',
      'packages/node_modules/repo-cooker-test/package.json',
      'packages/private-cooker/package.json',
    ],
  },
  {
    author: {
      name: 'Gaspard Bucher',
      email: 'gaspard@lucidogen.io',
    },
    date: '2017-06-29T12:47:42.000Z',
    sha: '3e9f0ff967855d62bbd5dc9a3ba3557357654641',
    body: '',
    issues: [],
    breaks: [],
    type: 'chore',
    scope: 'readme',
    message: 'update readme with another todo',
    files: ['README.md'],
  },
  {
    author: {
      name: 'Gaspard Bucher',
      email: 'gaspard@lucidogen.io',
    },
    date: '2017-06-29T14:51:08.000Z',
    sha: '06b4a9a31f5ac03f755c843388f6bddaec3ceaa8',
    body: '',
    issues: ['#1'],
    breaks: [],
    type: 'feat',
    scope: 'pastry-chef',
    message: 'pastry fixes issues',
    files: ['packages/node_modules/@repo-cooker-test/pastry-chef/README.md'],
  },
  {
    author: {
      name: 'Gaspard Bucher',
      email: 'gaspard@lucidogen.io',
    },
    date: '2017-06-29T14:52:44.000Z',
    sha: 'c465e3323fc2c63fbeb91f9b9b43379d28f9b761',
    body: '',
    issues: [],
    breaks: ['had to add milk'],
    type: 'fix',
    scope: 'commis',
    message: 'removed excessive salt',
    files: ['packages/node_modules/@repo-cooker-test/commis/README.md'],
  },
]
